ceviri
python/python-docs-tr pull request #102
Opened 2023-02-01 13:40 UTC by Yener07

3.11.

2023-02-01 14:23 UTC, egeakman commented on whatsnew/3.8.po
> +"açıklamaktadır. Tüm ayrıntılar için :bkz:`changelog <changelog> `a bakın."
```suggestion
"açıklamaktadır. Tüm ayrıntılar için :ref:`changelog` 'a bakın."
```

2023-02-01 14:26 UTC, egeakman commented
@Yener07 kendi forkunda Actions bölümünden `Wrap All` workflow'unu çalıştırabilir misin?

2023-02-01 14:36 UTC, egeakman requested changes

2023-02-01 14:36 UTC, egeakman commented on whatsnew/3.8.po
> +msgstr "Tam açıklama için :pep:`570`e bakın."
```suggestion
msgstr "Tam açıklama için :pep:`570` 'e bakın."
```

2023-02-01 14:36 UTC, egeakman commented on whatsnew/3.8.po
> +msgstr "Tam açıklama için :pep:`590`a bakın."
```suggestion
msgstr "Tam açıklama için :pep:`590` 'a bakın."
```

2023-02-01 16:50 UTC, ahmetveburak requested changes
Tamamini incelemedim fakat iyi bir sekilde gozden gecirilmesi gerekiyor. 
Eksik cevirilerin ve `islev` olarak cevirilen `function`'larin guncellenmesi lazim

2023-02-01 16:50 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"değerin ifade gövdesinde de gerekli olduğu liste kavrayışlarında ortaya çıkar::"
kavrayis yerine uretec daha mantikli olabilir
https://python-istihza.yazbel.com/listeler_ve_demetler.html#liste-uretecleri-list-comprehensions

2023-02-01 16:50 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"işlev parametresi sözdizimi ``/`` vardır. Bu, Larry Hastings'in `Argument "
islev > fonksiyon olmali.
genel ifade olarak da tekrar gozden gecirilmeli

2023-02-01 16:50 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"bağımsız değişkenlerini engellemektir.  For example, the builtin :func:`len` "
eksik ceviri mevcut

2023-02-01 16:50 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"gelecekte değiştirilebilir.  Bu, aşağıdaki işlev belirtimi ile mümkün olmuştur::"
butun islevler gozden gecirilmeli

2023-02-01 16:50 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"Keyword:`yield` ve :keyword:`return` ifadelerinde genelleştirilmiş "
:keyword: seklinde baslamali

2023-02-01 16:57 UTC, egeakman commented on whatsnew/3.8.po
> +"Keyword:`yield` ve :keyword:`return` ifadelerinde genelleştirilmiş "
@ahmetveburak yorumları suggestion şeklinde yapabilirsen (Ctrl+G) direkt commitleyebiliriz, daha rahat olur.

2023-02-01 17:12 UTC, ahmetveburak commented on whatsnew/3.8.po
> +"Keyword:`yield` ve :keyword:`return` ifadelerinde genelleştirilmiş "
@egeakman tamamdir :)

2023-02-02 19:33 UTC, Yener07 commented
Gözümden kaçmadıysa tüm build sıkıntılarının çözülmüş olması lazım.

2023-02-03 03:01 UTC, egeakman approved these changes

2023-02-03 03:02 UTC, merged