Library time
python/python-docs-tr pull request #125
Opened 2023-02-22 22:02 UTC by serkan-bayram

2023-02-22 22:07 UTC, egeakman commented on library/time.po
> +"wikipedia.org/wiki/Unix_time>` olarak anılır."
```suggestion
"epoch_ 'dan bu yana geçen süreyi kayan noktalı bir sayı olarak saniye "
"cinsinden döndürür. `leap seconds`_ 'ın ele alınması platforma bağlıdır. "
"Windows'ta ve çoğu Unix sisteminde, artık saniyeler, epoch_ 'dan bu yana "
"saniye cinsinden süreye dahil edilmez. Bu genellikle `Unix time <https://en."
"wikipedia.org/wiki/Unix_time>`_ olarak anılır."
```

2023-02-22 22:19 UTC, egeakman commented
Python belgeleri rST formatında yazıldığı için bazı noktalara dikkat etmemiz gerekiyor. Bunlardan bazılar:
- Back-tick (ters kesme işareti) (\`) arasına yazılmış kelimelere ek getirirken `` `asdasd asdasd`e `` yerine `` `asdasd asdasd`'e `` şeklinde araya kesme işareti koyarak yazmamız gerekiyor.

- Back-tick'li ifadelerden sonra alttan çizgi geliyorsa bu bir link veya referans olduğunu gösterir bu yüzden örneğin `` `epoch`_ `` şeklindeki ifade al çizgi bozulmadan `` `epoch`_ 'a `` şeklinde yazılabilir.

- Back-tick sayısının tutarlı olması gerekiyor. Yani back-tick'li ifade tek bt ile başladıysa tek bt ile bitmesi, çift ise çift ile bitmesi gerekir.

- Yıldız işaretleri italik veya kalın yazmak için kullanıldığından tekse tek çiftse çift yıldızla kapatılması gerekir. Örneğin ``*sth`` yerine ``*sth*``, ``sth**`` yerine ``**sth**`` gibi.

2023-02-22 22:22 UTC, serkan-bayram commented
Tamamdır bu dediklerinize dikkat ederek gözden geçiriyorum şu anda.

2023-02-22 22:24 UTC, egeakman requested changes

2023-02-22 22:24 UTC, egeakman commented on library/time.po
> +"en-us/windows-hardware/drivers/kernel/high-Definition-timers>` kullanır. "
```suggestion
"en-us/windows-hardware/drivers/kernel/high-Definition-timers>`_ kullanır. "
```

2023-02-22 22:24 UTC, egeakman commented on library/time.po
> +"dizeye dönüştürün: ``'Sun Jun 20 23:21:05 1993' ``. Gün alanı iki karakter "
```suggestion
"dizeye dönüştürün: ``'Sun Jun 20 23:21:05 1993'``. Gün alanı iki karakter "
```

2023-02-22 22:24 UTC, egeakman commented on library/time.po
> +"batısındaki DST olmayan saniyeler), `altzone`` (UTC'nin batısındaki DST "
```suggestion
"batısındaki DST olmayan saniyeler), ``altzone`` (UTC'nin batısındaki DST "
```

2023-02-22 22:24 UTC, egeakman commented on library/time.po
> +"file:`/usr/share/zoneinfo` konumunda bulunur. Örnek olarak, `'US/Eastern'``, "
```suggestion
"file:`/usr/share/zoneinfo` konumunda bulunur. Örnek olarak, ``'US/Eastern'``, "
```

2023-02-22 22:25 UTC, egeakman commented
> Tamamdır bu dediklerinize dikkat ederek gözden geçiriyorum şu anda.

Bu arada bu tarz hataları (özellikle back-tick ile ilgili olanları) VS Code'un arama kısmında regex kullanarak kolayca bulmak mümkün oluyor.

2023-02-22 22:32 UTC, serkan-bayram commented
Bu değişiklikleri nasıl gönderebilirim acaba yukarıda yaptığım gibi bir review uygun oluyor mu yoksa başka bir şey mi yapmam lazım

2023-02-22 22:35 UTC, egeakman commented
> Bu değişiklikleri nasıl gönderebilirim acaba yukarıda yaptığım gibi bir review uygun oluyor mu yoksa başka bir şey mi yapmam lazım

Direkt GitHub üzerinden review edebilirsiniz suggestion'larla veya localde tümden değiştirebilirsiniz. Size nasıl rahat oluyorsa.

2023-02-22 22:40 UTC, egeakman commented
Bu çıkan checklerin sonucunda nerelerde hata olduğunu daha rahat yakalayabilirsiniz. Örneğin https://github.com/python/python-docs-tr/actions/runs/4247504160/jobs/7385673983#step:5:571 burada kırmızı olan yerler çıkan hatalar. Buradaki hataların satır numarası entry numaralarına göre oluyor o yüzden örneğin 84. satır diyorsa,

```gettext-catalog
#: library/time.rst:84
```

olan satıra bakmanız gerekiyor.

sphinx-lint sonuçlarında normal satır numarası kullanılıyor, o yüzden 100. satır diyorsa kod editöründe görünen 100. satıra bakabilirsiniz.

2023-02-22 23:16 UTC, serkan-bayram commented
Tekrardan düzenledim ve pre-commit'ten geçti ama git kullanmayı çok iyi bilmediğimden dolayı tekrar yollamayı beceremedim buraya ek olarak koysam değiştirebiliyor musunuz?

https://drive.google.com/file/d/1Xw_tKsdkRE1xX8odkby03pNWcgpXiDWb/view?usp=share_link

2023-02-22 23:21 UTC, egeakman commented
> Tekrardan düzenledim ve pre-commit'ten geçti ama git kullanmayı çok iyi bilmediğimden dolayı tekrar yollamayı beceremedim buraya ek olarak koysam değiştirebiliyor musunuz?
> 
> https://drive.google.com/file/d/1Xw_tKsdkRE1xX8odkby03pNWcgpXiDWb/view?usp=share_link

Elinize sağlık. ``git push --force`` yapabilir misiniz?

2023-02-23 17:37 UTC, egeakman requested changes

2023-02-23 17:37 UTC, egeakman commented on library/time.po
> +# Copyright (C) 2001-2022, Python Software Foundation
```suggestion
# Copyright (C) 2001-2023, Python Software Foundation
```

2023-02-23 17:37 UTC, egeakman commented on library/time.po
> +"`sleep` sıfıra eşit olmayan kesirli zamanı kabul eder."
```suggestion
"`sleep` sıfıra eşit olmayan kesirli zamanı kabul eder (Unix :c:func:`select`, "
"mümkün olduğunda bunu uygulamak için kullanılır)."
```

2023-02-23 17:37 UTC, egeakman commented on library/time.po
> +"bir listesi için :ref:`time-clock-id-constanst`'a bakınız."
```suggestion
"bir listesi için :ref:`time-clock-id-constants`'a bakınız."
```

2023-02-23 17:38 UTC, egeakman commented on library/time.po
> +"uygun değerlerin bir listesi için :ref:`time-clock-id-constanst`'a bakınız."
```suggestion
"uygun değerlerin bir listesi için :ref:`time-clock-id-constants`'a bakınız."
```

2023-02-24 07:50 UTC, egeakman requested changes

2023-02-24 07:50 UTC, egeakman commented on library/time.po
> +msgstr "Ya da ```select()`` kullanın (netlik: 1 mikrosaniye)."
```suggestion
msgstr "Ya da ``select()`` kullanın (netlik: 1 mikrosaniye)."
```

2023-02-24 07:50 UTC, egeakman commented on library/time.po
> +"yakın kesinlik sağlayabilen bir ``CLOCK_HIGHRES`` zamanlayıcıya sahiptir."
```suggestion
"yakın kesinlik sağlayabilen bir ``CLOCK_HIGHRES`` zamanlayıcıya sahiptir. "
```

2023-02-24 07:54 UTC, egeakman approved these changes
Elinize sağlık 😊

2023-02-24 08:10 UTC, merged

2023-02-24 09:24 UTC, serkan-bayram commented
Teşekkürler sizin de elinize sağlık :)