Math kütüphanesi tamamlandı.
python/python-docs-tr pull request #130
Opened 2023-03-30 21:03 UTC by berkcangumusisik

2023-03-31 14:09 UTC, egeakman requested changes

2023-03-31 14:09 UTC, egeakman commented on library/math.po
> +"işlevini döndürür."
```suggestion
"*x* adresindeki `hata "
"fonksiyonunu <https://en.wikipedia.org/wiki/Error_function>`_ döndürür."
```

2023-03-31 14:09 UTC, egeakman commented on library/math.po
> +"değerleri için kullanılır."
```suggestion
"*x* 'de tamamlayıcı hata fonksiyonunu döndürür.  `Tamamlayıcı hata fonksiyonu "
"<https://en.wikipedia.org/wiki/Error_function>`_ ``1.0 - erf(x)`` olarak "
"tanımlanır.  Birbirinden çıkarmanın `anlamlılık kaybına <https://en.wikipedia.org/wiki/"
"Loss_of_significance>`_ neden olacağı büyük *x* "
"değerleri için kullanılır.\\"
```

2023-03-31 14:09 UTC, egeakman commented on library/math.po
> +"eşdeğerdir. IEEE-754 standardının <https://en.wikipedia.org/wiki/IEEE_754>`_ "
```suggestion
"eşdeğerdir. `IEEE-754 standardının <https://en.wikipedia.org/wiki/IEEE_754>`_ "
```

2023-04-16 21:33 UTC, egeakman commented
@berkcangumusisik  Selam, review geciktiği için kusura bakmayın. Bazı syntax hataları fark ettim. Aşağıdaki yorumlardaki adımları uygukayarak hata olan yerlere bakabilir misiniz? Aklınıza takılan bir yer olursa yazmaktan çekinmeyin.

- https://github.com/python/python-docs-tr/pull/125#issuecomment-1440928283

- https://github.com/python/python-docs-tr/pull/125#issuecomment-1440895580

- https://github.com/python/python-docs-tr/pull/125#issuecomment-1440888022

2023-04-17 07:19 UTC, berkcangumusisik commented
Nasıl yapacağımı çözemedim destek olabilir misiniz

2023-04-17 13:06 UTC, egeakman commented
> Nasıl yapacağımı çözemedim destek olabilir misiniz

Tabii ki. Nerede sorun yaşadınız?

2023-04-17 13:15 UTC, egeakman requested changes

2023-04-17 13:15 UTC, egeakman commented on library/math.po
> +"to 'pick apart' the internal representation of a float in a portable way."
Orijinal textleri değiştirmeye gerek yok.

```suggestion
"to \"pick apart\" the internal representation of a float in a portable way."
```

2023-04-17 13:15 UTC, egeakman commented on library/math.po
> +"sağlayan `1e-09` değeridir.  *rel_tol* sıfırdan büyük olmalıdır."
Bu hali doğruydu.

```suggestion
"sağlayan ``1e-09`` değeridir.  *rel_tol* sıfırdan büyük olmalıdır."
```

2023-04-17 13:15 UTC, egeakman commented on library/math.po
> +"Tekrarlama olmadan ve sırayla n öğe arasından k öğeyi seçmenin "
Bu şekilde sıkıntı yok.

```suggestion
"Tekrarlama olmadan ve sırayla *n* öğe arasından *k* öğeyi seçmenin "
```

2023-04-17 13:28 UTC, egeakman requested changes
Bunları incelerseniz bazı hata çeşitlerini görebilirsiniz. Genellikle referansların başındaki iki nokta eksik kalmış. Doğru syntax örnekleri aşağıdaki gibi:

```diff
- func:`asdasd`
+ :func:`asdasd`
```

```diff
- :func:asdasd
+ :func:`asdasd`
```

```diff
- :func:`asdasd
+ :func:`asdasd`
```

```diff
- :func:`asdasd`daki
+ :func:`asdasd` 'daki
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"çağrı modeline sahip olduğuna dikkat edin: tek bir argüman alırlar ve ikinci "
```suggestion
":func:`frexp` ve :func:`modf`` 'un C'deki eşdeğerlerinden farklı bir çağrı/"
"dönüş modeline sahip olduğuna dikkat edin: tek bir argüman alırlar ve ikinci "
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"func:`ceil`, :func:`floor` ve :func:`modf` fonksiyonları için, yeterince "
```suggestion
":func:`ceil`, :func:`floor` ve :func:`modf` fonksiyonları için, yeterince "
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"``pi/4``tür, ancak ``atan2(-1, -1)`` ``-3*pi/4``tür."
```suggestion
"pozitif X ekseni ile bu açıyı yapar. :func:`atan2` 'nin amacı, her iki girdinin "
"de işaretlerinin bilinmesidir, böylece açı için doğru kadranı "
"hesaplayabilir. Örneğin, ``atan(1)`` ve ``atan2(1, 1)`` her ikisi de "
"``pi/4`` 'tür, ancak ``atan2(-1, -1)`` ``-3*pi/4`` 'tür."
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"gibi geleneksel istatistiksel fonksiyonları hesaplamak için kullanılabilir:"
```suggestion
":func:`erf` fonksiyonu, `kümülatif standart normal dağılım <https://en."
"wikipedia.org/wiki/Normal_distribution#Cumulative_distribution_functions>`_: "
"gibi geleneksel istatistiksel fonksiyonları hesaplamak için kullanılabilir::"
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"mod:`math` modülü çoğunlukla platform C matematik kütüphanesi fonksiyonları "
```suggestion
":mod:`math` modülü çoğunlukla platform C matematik kütüphanesi fonksiyonları "
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"Herhangi bir argümanın negatif olması durumunda :exc:ValueError fırlatır."
```suggestion
"Herhangi bir argümanın tamsayı olmaması durumunda :exc:`TypeError` yükseltir. "
"Herhangi bir argümanın negatif olması durumunda :exc:`ValueError` yükseltir."
```

2023-04-17 13:28 UTC, egeakman commented on library/math.po
> +"exc:ValueError fırlatır."
```suggestion
"exc:`ValueError` fırlatır."
```

2023-04-17 16:34 UTC, berkcangumusisik commented
Şimdi halledeceğim onaya yollamadan izin vermedi hataları görmeye

2023-04-17 17:09 UTC, berkcangumusisik commented
Şu an hallettim gözüküyor ama bir kontrolünüzü rica edebilir miyim

2023-04-17 17:14 UTC, egeakman commented
> Şu an hallettim gözüküyor ama bir kontrolünüzü rica edebilir miyim

```
library/math.po:144: inline literal missing (escaped) space after literal: '``-1e-100``d' (missing-space-after-literal)
library/math.po:144: inline literal missing (escaped) space after literal: '``1e100-1e-100``d' (missing-space-after-literal)
library/math.po:735: inline literal missing (escaped) space after literal: '``-3*pi/4``t' (missing-space-after-literal)
library/math.po:144: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:144: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:144: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:144: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:360: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:735: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
library/math.po:735: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
```

Bunlar kalmış görünüyor.

2023-04-20 06:24 UTC, berkcangumusisik commented
@egeakman tamamladım kontrolünü rica edebilir miyim?

2023-04-21 12:58 UTC, egeakman commented on library/math.po
> +"x * (2**i)`` döndürür.  Bu aslında :func:`frexp` fonksiyonunun tersidir."
```suggestion
"``x * (2**i)`` döndürür.  Bu aslında :func:`frexp` fonksiyonunun tersidir."
```

Bu sonuncusu

2023-04-21 13:31 UTC, egeakman commented
Elinize sağlık! Belgenin yeni hali yarın resmi sitede yayına girer. O zamana kadar aşağıdaki linkten bakabilirsiniz:

https://python-docs-tr.readthedocs.io/tr/3.11/library/math.html

2023-04-21 13:32 UTC, egeakman approved these changes

2023-04-21 13:33 UTC, merged