Tamamlandı: clinic.po
python/python-docs-tr pull request #143
Opened 2023-05-01 22:38 UTC by Yener07

Hata varsa af ola

2023-05-01 22:40 UTC, Yener07 commented
backtick'e kesme işareti değiyor bazı yerlerde, onları düzeltip tekrar açarım.

2023-05-01 23:01 UTC, mertssmnoglu commented
> backtick'e kesme işareti değiyor bazı yerlerde, onları düzeltip tekrar açarım.

@Yener07 Merhaba, dilersen yeni pull request açmadan bunun üzerinden değişiklik yapabilirsin. Tek yapman gereken bu branch'e commitlemek ve pushlamak.

2023-05-02 07:54 UTC, egeakman commented
> backtick'e kesme işareti değiyor bazı yerlerde, onları düzeltip tekrar açarım.

Backtick'e kesme işaretinin değmesi sorun yaratmıyor. Sıkıntı yok yani.

2023-05-02 08:08 UTC, egeakman requested changes

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"``{number}` grubun gerekli parametrelerden ne kadar uzakta olduğunu gösteren "
```suggestion
"``{number}`` grubun gerekli parametrelerden ne kadar uzakta olduğunu gösteren "
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +msgstr "``{block comment end}`"
```suggestion
msgstr "``{block comment end}``"
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"İsteğe bağlı gruplar *sadece* :c:func:`PyArg_ParseTuple'a birden fazla çağrı "
```suggestion
"İsteğe bağlı gruplar *sadece* :c:func:`PyArg_ParseTuple`'a birden fazla çağrı "
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +" ``Modules/_threadmodule.c`` içindeki ``setattro`` slot yönteminden örnek::"
```suggestion
"Slot metotları ile ``defining_class`` kullanmak mümkün değildir.  Bu tür "
"yöntemlerden modül durumunu almak için, modülü aramak için :c:func:"
"`PyType_GetModuleByDef` ve ardından modül durumunu almak için :c:func:"
"`PyModule_GetState` kullanın. ``Modules/_threadmodule.c`` içindeki "
"``setattro`` slot yönteminden örnek::"
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"hesaplar, sonra son anda onu ``PyObject *``e dönüştürür.  Argüman Kliniği "
```suggestion
"hesaplar, sonra son anda onu ``PyObject *``'e dönüştürür.  Argüman Kliniği "
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"fonksiyonunuzu değiştirir, ardından bu değeri uygun ``PyObject *``e "
```suggestion
"fonksiyonunuzu değiştirir, ardından bu değeri uygun ``PyObject *``'e "
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"kullanırken yaptığınız gibi sonuna yakın ``buffer``ı boşaltın."
```suggestion
"kullanırken yaptığınız gibi sonuna yakın ``buffer``'ı boşaltın."
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"benzer, ancak ``buffer``dan daha az düzenleme gerektirebilir.  Dosyanızın "
```suggestion
"benzer, ancak ``buffer``'dan daha az düzenleme gerektirebilir.  Dosyanızın "
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"pass``a yazar, diğer her şeyi ``buffer``a yazar."
```suggestion
"Impl_prototype``'ı bastırır, ``impl_definition``'ı ``block``'a yazar, "
"``docstring_prototype``, ``methoddef_define`` ve ``parser_prototype``'ı ``two-"
"pass``'a yazar, diğer her şeyi ``buffer``'a yazar."
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"doğru boşaltın."
```suggestion
"``buffer`` ön ayarına benzer, ancak ``block``'a daha fazla şey yazar, "
"yalnızca oluşturulan kodun gerçekten büyük parçalarını ``buffer``'a yazar. "
"Bu, bloğun çıktısında biraz daha fazla şey olması gibi küçük bir maliyetle, "
"``buffer``'ın kullanımdan önce tanımlama sorununu tamamen ortadan kaldırır. "
"Tıpkı ``buffer`` ön ayarını kullanırken yaptığınız gibi, ``buffer``'ı sonuna "
"doğru boşaltın."
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +msgstr "Dördüncü yeni yönerge ``set``tir:"
```suggestion
msgstr "Dördüncü yeni yönerge ``set``'tir:"
```

2023-05-02 08:08 UTC, egeakman commented on howto/clinic.po
> +"döndürülür.  DecodeFSDefault`` için dönüş türü ``const char *``'dır; bir "
```suggestion
"döndürülür.  ``DecodeFSDefault`` için dönüş türü ``const char *``'dır; bir "
```

2023-05-02 08:12 UTC, egeakman commented on howto/clinic.po
> +"Impl_prototype``'ı bastırır, ``impl_definition``'ı ``block``'a yazar, "
```suggestion
"``impl_prototype``'ı bastırır, ``impl_definition``'ı ``block``'a yazar, "
```

2023-05-02 08:40 UTC, egeakman requested changes

2023-05-02 08:40 UTC, egeakman commented on howto/clinic.po
> +"*blok*tur.  (Argüman Kliniği tarafından henüz başarılı bir şekilde "
```suggestion
"*blok*'tur.  (Argüman Kliniği tarafından henüz başarılı bir şekilde "
```

2023-05-02 08:40 UTC, egeakman commented on howto/clinic.po
> +"Gelecekte :c:func:`PyArg_ParseTuple`ın desteklediğiyle sınırlı olmayan yeni "
```suggestion
"Gelecekte :c:func:`PyArg_ParseTuple`'ın desteklediğiyle sınırlı olmayan yeni "
```

2023-05-02 08:40 UTC, egeakman commented on howto/clinic.po
> +"``PyArg_Parse`` çağrısı yazarken, teorik olarak :c:func:`PyArg_ParseTuple`a "
```suggestion
"``PyArg_Parse`` çağrısı yazarken, teorik olarak :c:func:`PyArg_ParseTuple`'a "
```

2023-05-02 09:34 UTC, egeakman approved these changes

2023-05-02 09:35 UTC, egeakman commented
@Yener07 Eline sağlık!

2023-05-02 09:35 UTC, merged