Translate extending-index with machine translation
python/python-docs-tr pull request #78
Opened 2023-01-11 21:43 UTC by egeakman

Translated extending/index.po with [machine translation](https://github.com/python/python-docs-tr/blob/dddb1c28e96c4b1a9621f451b109d4318b871608/scripts/translate.py)

This is a test case for the new machine translation script. Human review is always required for machine translations.

2023-01-11 21:54 UTC, MorphaxTheDeveloper reviewed
nice

2023-01-11 21:54 UTC, MorphaxTheDeveloper commented on extending/index.po
> +"`Python Packaging User Guide: Binary Extensions "
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantıları "

2023-01-11 21:59 UTC, MorphaxTheDeveloper reviewed
try

2023-01-11 21:59 UTC, MorphaxTheDeveloper commented on extending/index.po
> +"`Python Packaging User Guide: Binary Extensions "
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```suggestion
"`Python Packaging User Guide: Binary Extensions "
```

2023-01-11 22:02 UTC, MorphaxTheDeveloper reviewed
ok.

2023-01-11 22:02 UTC, MorphaxTheDeveloper commented on extending/index.po
> +"`Python Packaging User Guide: Binary Extensions "
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```

2023-01-14 23:54 UTC, Ardasak requested changes
After those changes, LGTM!

2023-01-14 23:54 UTC, Ardasak commented on extending/index.po
> +"kullanılmak üzere başka bir uygulamaya nasıl yerleştirileceğini açıklar. Son"
```suggestion
"kullanılmak üzere başka bir uygulamaya nasıl yerleştirileceğini de açıklar. Son"
```

2023-01-14 23:54 UTC, Ardasak commented on extending/index.po
> +"Bu belge, Python hakkında temel bilgileri varsayar. Dile gayri resmi bir "
```suggestion
"Bu belge, Python hakkında temel bilgileri ele alır Dile gayri resmi bir "
```

2023-01-14 23:54 UTC, Ardasak commented on extending/index.po
> +"<https://numba.pydata.org/>`_, `Numba <https://numba.pydata.org/>`_, `Numba "
```suggestion
"Bu kılavuz, yalnızca CPython'un bu sürümünün bir parçası olarak sağlanan "
"uzantıları oluşturmak için temel araçları kapsar. `Cython "
"<https://cython.org/>`_, `cffi <https://cffi.readthedocs.io>`_, `SWIG <https://www."
"swig.org>`_ ve `Numba <https://numba.pydata.org/>`_ gibi "
"üçüncü taraf araçlar, Python için C ve C++ uzantıları oluşturmaya yönelik "
"hem daha basit hem de daha karmaşık yaklaşımlar sunar."
```

2023-01-14 23:55 UTC, Ardasak requested changes
Oops

2023-01-14 23:55 UTC, Ardasak commented on extending/index.po
> +"hem daha basit hem de daha karmaşık yaklaşımlar sunar."
```suggestion
"Bu kılavuz, yalnızca CPython'un bu sürümünün bir parçası olarak sağlanan "
"uzantıları oluşturmak için temel araçları kapsar. `Numba "
"Bu kılavuz, yalnızca CPython'un bu sürümünün bir parçası olarak sağlanan "
"uzantıları oluşturmak için temel araçları kapsar. `Cython "
"<https://cython.org/>`_, `cffi <https://cffi.readthedocs.io>`_, `SWIG <https://www."
"swig.org>`_ ve `Numba <https://numba.pydata.org/>`_ gibi "
"üçüncü taraf araçlar, Python için C ve C++ uzantıları oluşturmaya yönelik "
"hem daha basit hem de daha karmaşık yaklaşımlar sunar."
```

2023-01-15 00:01 UTC, Ardasak requested changes
oops again

2023-01-15 00:01 UTC, Ardasak commented on extending/index.po
> +"hem daha basit hem de daha karmaşık yaklaşımlar sunar."
```suggestion
"Bu kılavuz, yalnızca CPython'un bu sürümünün bir parçası olarak sağlanan "
"uzantıları oluşturmak için temel araçları kapsar. `Cython "
"<https://cython.org/>`_, `cffi <https://cffi.readthedocs.io>`_, `SWIG <https://www."
"swig.org>`_ ve `Numba <https://numba.pydata.org/>`_ gibi "
"üçüncü taraf araçlar, Python için C ve C++ uzantıları oluşturmaya yönelik "
"hem daha basit hem de daha karmaşık yaklaşımlar sunar."
```

2023-01-15 00:02 UTC, Ardasak approved these changes

2023-01-15 00:03 UTC, egeakman commented on extending/index.po
> +"Bu belge, Python hakkında temel bilgileri ele alır Dile gayri resmi bir "
```suggestion
"Bu belge, Python hakkında temel bilgiye sahip olduğunuzu varsayar. Dile gayri resmi bir "
```

2023-01-15 00:16 UTC, merged