machine translated: installing/index
python/python-docs-tr pull request #90
Opened 2023-01-16 01:50 UTC by egeakman

Bazı satırlarda düzeltilmesi gerekn büyük sorunlar. Dikkatli review edilmesi gerekiyor.

2023-01-19 04:24 UTC, Ardasak requested changes

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"olarak kendi çözümlerine katkıda bulunmasına olanak tanır."
```suggestion
"Bu, Python kullanıcılarının etkin bir şekilde paylaşımda bulunmasına ve "
"işbirliği yapmasına, başkalarının yaygın (ve hatta bazen nadir!) sorunlara "
"yönelik oluşturduğu çözümlerden faydalanmasına ve potansiyel olarak ortak havuza "
"kendi çözümleriyle katkıda bulunmasına olanak tanır."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"index>`'a bakın."
```suggestion
"Bu kılavuz, sürecin kurulum kısmını kapsar. Kendi Python projelerinizi "
"oluşturma ve paylaşma kılavuzu için :ref:`distribution rehberine <distributing-"
"index>` 'a bakın."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanırken lütfen bu tür politikaları dikkate alın."
```suggestion
"Kurumsal kullanıcılar, birçok kuruluşun açık kaynak yazılımları "
"kullanma ve bunlara katkıda bulunma konusunda kendi politikaları"
" olduğunu unutmayın. Python ile sağlanan dağıtım ve kurulum araçlarını "
"kullanırken lütfen bu tür politikaları dikkate alın."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"yalıtılmış bir Python ortamıdır."
```suggestion
"izole bir Python ortamıdır."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +" tüm oluşturulan sanal ortamlara yüklenmesi varsayılandır."
```suggestion
"``venv``, sanal ortamlar oluşturmaya yönelik standart bir araçtır ve Python "
"3.3'ten beri Python'un bir parçasıdır. Python 3.4'ten başlayarak, ``pip`` 'in"
" tüm oluşturulan sanal ortamlara yüklenmesi varsayılandır."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanılmasına izin verir."
```suggestion
"``virtualenv``, ``venv`` 'in üçüncü taraf alternatifidir (ve öncülüdür). ``venv`` 'i "
"hiç sağlamayan veya oluşturulan ortamlara ``pip`` 'i otomatik olarak "
"yükleyemeyen 3.4'ten önceki Python sürümlerinde sanal ortamların "
"kullanılmasına izin verir."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"izleyicileri bulundururlar."
```suggestion
"`Python Packaging Authority <https://www.pypa.io/>`__, standart paketleme araçlarının "
"ve ilişkili meta veri ve dosya biçimi standartlarının bakımından ve "
"geliştirilmesinden sorumlu geliştiriciler ve belge yazarları grubudur. Hem "
"`GitHub <https://github.com/pypa>`__ hem de `Bitbucket "
"<https://bitbucket.org/pypa/>`__ 'ta çeşitli araçlar, dokümantasyon ve sorun "
"izleyicileri bulundururlar."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanılan posta listesinin adı gibi)."
```suggestion
"``distutils``, Python standart kitaplığına ilk olarak 1998 yılında eklenen "
"orijinal oluşturma ve dağıtım sistemidir. ``distutils`` 'in doğrudan "
"kullanımı aşamalı olarak kaldırılırken, mevcut paketleme ve dağıtım "
"altyapısının temelini atmaya devam etmektedir, ve yalnızca standard kütüphanenin bir "
"parçası olmakla kalmamakla birlikte adı başka şekillerde de yaşıyor"
" (Python paketleme standartlarının geliştirilmesini koordine etmek için "
"kullanılan posta listesinin adı gibi)."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"Artık sanal ortamlar oluşturmak için ``venv``'ün kullanılması önerilir."
```suggestion
"Artık sanal ortamlar oluşturmak için ``venv`` 'in kullanılması önerilir."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"`Python Packaging User Guide: Creating and using virtual environments "
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: Sanal ortamları oluşturma ve kullanma  "
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"Paket Dizininden yükleyecektir:"
```suggestion
"Paket Dizininden yükleyecektir::"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"``<``, ``<`` gibi karşılaştırma işleçleri veya kabuk tarafından yorumlanan "
```suggestion
"``>``, ``<`` gibi karşılaştırma operatörleri veya kabuk tarafından yorumlanan "
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +" User Guide <https://packaging.python.org>`__'te bulunabilir."
```suggestion
"``pip`` ve yapabilecekleri hakkında daha fazla bilgi ve kaynak `Python Paketleme"
" Kullanıcı Kılavuzu <https://packaging.python.org>`__ 'nda bulunabilir."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"<https://packaging.python.org/installing/>`__"
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: Python Dağıtma Paketlerini Kurma "
"<https://packaging.python.org/installing/>`__"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "Bunlar, bazı genel görevler için hızlı cevaplar veya bağlantılar."
```suggestion
msgstr "Bunlar, bazı genel görevler için hızlı cevaplar veya bağlantılardır."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "... ``pip``'ü Python 3.4'ten önceki Python sürümlerinde kurun mu?"
```suggestion
msgstr "... ``pip`` 'i Python 3.4'ten önceki Python sürümlerinde kurmalı mı?"
```

@egeakman

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"açıklandığı gibi \"önyüklenmesi\" gerekir."
```suggestion
"Python, ``pip`` 'i yalnızca Python 3.4 ile paketlemeye başladı. Önceki "
"sürümler için, ``pip`` 'in Python Paketleme Kullanıcı Kılavuzu'nda "
"açıklandığı gibi \"önyüklenmesi\" gerekir."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"packages>`__"
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: Paketleri Kurmak için Gerekenler "
"<https://packaging.python.org/installing/#requirements-for-installing-"
"packages>`__"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "... sadece mevcut kullanıcı için paketler kurulsun mu?"
```suggestion
msgstr "... sadece mevcut kullanıcı için paketler kurabilirim?"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "... bilimsel Python paketleri kurulsun mu?"
```suggestion
msgstr "... bilimsel Python paketleri kurabilirim?"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"için bir paket yükleyecektir."
```suggestion
"``--user`` seçeneğinin ``python -m pip install`` 'e geçirilmesi, "
" sistemin tüm kullanıcıları yerine yalnızca geçerli kullanıcı "
"için bir paket yükleyecektir."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"`Python Packaging User Guide: Binary Extensions "
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kalmadan edinmeye de yardımcı olabilir."
```suggestion
"`bilimsel yazılım <https://packaging.python.org/science/>`__ 'ı yüklemek "
"için önceden oluşturulmuş ``teker`` dosyaları olarak henüz mevcut olmayan "
"çözümlerden bazıları, diğer ikili uzantıları yerel olarak kurmaya gerek "
"kalmadan edinmeye de yardımcı olabilir."
```

@egeakman

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kendilerinin inşa etmesi gerekmek yerine."
```suggestion
"İkili ``teker`` formatı için desteğin sunulması ve Python Paket Dizini "
"aracılığıyla en azından Windows ve macOS için tekerler yayınlama yeteneği"
" ile, kullanıcılar önceden oluşturulmuş uzantıları kendileri inşa etmek yerine daha "
"düzenli bir şekilde yükleyebildiğinden bu sorunun zaman içinde azalması bekleniyor."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "İkili uzantıları yükleme"
```suggestion
msgstr "İkili uzantıları kurma"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kaynaklar da vardır."
```suggestion
"`installing pip.  <https://packaging.python.org/en/latest/tutorials/installing-"
"packages/#ensure-pip-setuptools-and-wheel-are-up-to-date>`__"
"için ek kaynaklar da vardır."
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"``pip``'ün varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```suggestion
"``pip`` 'in varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kurulumu dahil edilir. Bu Python kurulumuna kurulum, sisteme root erişimi "
@egeakman

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "Python'u Linux'ta sisteme kurmak"
```suggestion
msgstr "Python'u Linux'de sisteme kurmak"
```

@egeakman

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanın::"
```suggestion
"Windows'ta, ``py`` Python başlatıcısını ``-m`` anahtarıyla birlikte "
"kullanın::"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanın::"
```suggestion
"Linux, macOS ve diğer POSIX sistemlerinde, ``pip`` 'in uygun kopyasını "
"çalıştırmak için ``-m`` anahtarıyla birlikte sürümlü Python komutlarını "
"kullanın::"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +msgstr "... paralel olarak yüklenmiş birden çok Python sürümüyle çalışmak?"
```suggestion
msgstr "... paralel olarak yüklenmiş birden çok Python sürümüyle çalışabilirim?"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"<https://packaging.python.org/science/>`__"
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: Bilimsel Paketler Kurma "
"<https://packaging.python.org/science/>`__"
```

2023-01-19 04:24 UTC, Ardasak commented on installing/index.po
> +"kullanıcıların bu paketleri ``pip`` ile kurmaya çalışmak yerine `other means"
@egeakman other means

2023-01-19 07:44 UTC, egeakman commented on installing/index.po
> +"kullanıcıların bu paketleri ``pip`` ile kurmaya çalışmak yerine `other means"
```suggestion
"kullanıcıların bu paketleri ``pip`` ile kurmaya çalışmak yerine `başka yollar"
```

2023-01-19 07:49 UTC, egeakman commented on installing/index.po
> +"kurulumu dahil edilir. Bu Python kurulumuna kurulum, sisteme root erişimi "
```suggestion
"kurulumu dahil edilir. Bu Python kurulumuna paket yüklemek, sisteme root erişimi "
```

2023-01-19 07:50 UTC, egeakman commented on installing/index.po
> +"yükseltilirse, sistem paketi yöneticisinin ve sistemin diğer bileşenlerinin "
```suggestion
"güncellenirse, sistem paketi yöneticisinin ve sistemin diğer bileşenlerinin "
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"kendilerinin inşa etmesi gerekmek yerine."
```suggestion
"İkili ``wheel`` formatı için desteğin sunulması ve Python Paket Dizini "
"aracılığıyla en azından Windows ve macOS için wheel'lar yayınlanabilmesi "
"ile, kullanıcılar önceden oluşturulmuş uzantıları kendileri inşa etmek yerine daha "
"düzenli bir şekilde yükleyebildiğinden bu sorunun zaman içinde azalması bekleniyor."
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"kaynaklar da vardır."
```suggestion
"`pip'i yüklemek  <https://packaging.python.org/en/latest/tutorials/installing-"
"packages/#ensure-pip-setuptools-and-wheel-are-up-to-date>`__"
"için ek kaynaklar da vardır."
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"``pip``'ün varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```suggestion
"``pip`` 'in varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"kurulumu dahil edilir. Bu Python kurulumuna kurulum, sisteme root erişimi "
```suggestion
"kurulumu dahil edilir. Bu Python kurulumuna paket yüklemek, sisteme root erişimi "
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"kalmadan edinmeye de yardımcı olabilir."
```suggestion
"`Bilimsel yazılımı <https://packaging.python.org/science/>`__ yüklemek "
"için önceden oluşturulmuş (pre-built) ``wheel`` dosyaları olarak henüz mevcut olmayan "
"çözümlerden bazıları, diğer ikili uzantıları yerel olarak kurmaya gerek "
"kalmadan edinmeye de yardımcı olabilir."
```

2023-01-19 08:12 UTC, egeakman commented on installing/index.po
> +"`Python Packaging User Guide: Binary Extensions "
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```

2023-01-19 08:23 UTC, egeakman commented on installing/index.po
> +"kurulumu dahil edilir. Bu Python kurulumuna kurulum, sisteme root erişimi "
```suggestion
"kurulumu dahil edilir. Bu Python kurulumuna paket yüklemek, sisteme root erişimi "
```

2023-01-19 08:23 UTC, egeakman commented on installing/index.po
> +"``pip``'ün varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```suggestion
"``pip`` 'in varsayılan olarak yüklenmemesi mümkündür. Bir olası düzeltme::"
```

2023-01-19 08:24 UTC, egeakman commented on installing/index.po
> +"kaynaklar da vardır."
```suggestion
"`pip'i yüklemek  <https://packaging.python.org/en/latest/tutorials/installing-"
"packages/#ensure-pip-setuptools-and-wheel-are-up-to-date>`__"
"için ek kaynaklar da vardır."
```

2023-01-19 08:24 UTC, egeakman commented on installing/index.po
> +"kendilerinin inşa etmesi gerekmek yerine."
```suggestion
"İkili ``wheel`` formatı için desteğin sunulması ve Python Paket Dizini "
"aracılığıyla en azından Windows ve macOS için wheel'lar yayınlanabilmesi "
"ile, kullanıcılar önceden oluşturulmuş uzantıları kendileri inşa etmek yerine daha "
"düzenli bir şekilde yükleyebildiğinden bu sorunun zaman içinde azalması bekleniyor."
```

2023-01-19 08:25 UTC, egeakman commented on installing/index.po
> +"`Python Packaging User Guide: Binary Extensions "
```suggestion
"`Python Paketleme Kullanıcı Kılavuzu: İkili Uzantılar "
```

2023-01-21 05:36 UTC, Ardasak submitted a review, later dismissed

2023-01-21 13:38 UTC, merged